services:
  assaultcubeserver:
    image: synergy90/assaultcube-server
    container_name: assaultcubeserver
    ports:
      - 28763:28763/udp
      - 28764:28764/udp
    environment:
      PLAYERCOUNT: 8
      SERVER_DESCRIPTION: synergy2k_AssaultCube_server
      SERVER_MODT: Greetings_from_synergy2k
      MASTER_PASSWORD: synergy2k
      GAME_PARAMS: -c${PLAYERCOUNT} -n${SERVER_DESCRIPTION} -o${SERVER_MODT} -x${MASTER_PASSWORD}
      UMASK: 000
      UID: 99
      GID: 100
      USER: assaultcuber
      DATA_PERM: 770
    restart: unless-stopped
